---

services:
  kafka:
    image: apache/kafka:3.8.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    networks:
      - app

  db:
    image: postgres:15.8-alpine
    container_name: vanilla-kotlin-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    networks:
      - app
    volumes:
      - ./db-migration/initdb.d/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app:
